# Generated by Django 5.1.6 on 2025-02-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPIs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inventory',
            field=models.CharField(default='Book', max_length=255),
        ),
    ]
