# Generated by Django 5.1.6 on 2025-02-25 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LemonAPI', '0002_category_menuitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='LemonAPI.category'),
        ),
    ]
